FROM ubuntu:20.04

# Mettre à jour le système et installer les dépendances nécessaires pour Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    iproute2 \
    && apt-get clean

# Installer pymodbus via pip
RUN pip3 install pymodbus

# Définir le répertoire de travail
WORKDIR /app

# Copier le script Python dans le conteneur
COPY plc1.py /app/plc1.py

# Commande par défaut pour exécuter le script
CMD ["python3", "plc1.py"]
